#! /usr/bin/perl
use strict;
use warnings;

# Where to read local configuration:
my $pokinom_config = 'pokinom.config';
if ($ARGV[0]) {
    $pokinom_config = $ARGV[0]
}

########################################
# Settings
########################################
# Possible mount points:
my @usable_mount_points;

# Other settings from $pokinom_config, not used here.
my $path_under_mount_point;
my $path_under_mount_point_backed_up;
my $path_under_mount_point_being_deleted;
my $destination;
my $rsync_username;
my $rsync_password;
my $rsync_log_prefix;
my $interrupted_prefix;
my $shut_down_when_done;
my $shut_down_action;
my $rsync_partial_dir_name;

# Local changes to the above.
eval `cat $pokinom_config`;

if (qx(whoami) eq "root\n") {
    qx(killall pokinom &> /dev/null);
# Find checkable (i.e. mounted) disks
    my @mount_output = qx/mount/;
    my %devices;
    map {
	my ($device, $mount_point) = /(\S+) on (.*) type .*/;
	map {
	    if ($_ eq $mount_point) {
		$devices{$mount_point} = $device;
	    }
	} @usable_mount_points;
    } @mount_output;
    map {
	my $device = $devices{$_};
        qx(umount $device && fsck -fp $device);
    } keys %devices;
} else {
    print "$0: only root can run this.\n";
}
